name: examen
description: Aplicaci贸n unificada con Mensajer铆a y Calculadora
publish_to: 'none' # No se publica en pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #  Dependencias para el m贸dulo de Mensajer铆a
  provider: ^6.1.1
  dio: ^5.4.0
  cached_network_image: ^3.3.1
  intl: ^0.18.1

  # Dependencias para el m贸dulo de Calculadora
  get: ^4.6.6

  #  conos de estilo iOS (usados por defecto en Flutter)
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #  Im谩genes o recursos que usa la aplicaci贸n
  assets: []
